language: java
jdk: oraclejdk8

env:
  global:
    - SONATYPE_USERNAME=nekomatic
    - secure: "LDhoRTAMboqKZPYOBw15k6YjGBQ6efhjY1YZ4BoFV3SBZXCqSBaWPSmtq6p08NpK3ceJgMrpSrkmui2W7rob7SPuBTmdpN3mm/OgZFXSMUGHY2sFaztup+TDk/NNPMwVaDFKlgj/dWzHlKHfLhI0etreSssP85wB7l13g9SXSirwwM62Tdf6IWk/Rl/IOSAF+YLV/tqWXuZ4Vik5GHQKK60Xh3/ZrR3Q4gQhR0hTBMOlBI4+uRNgjnPuzExz20Um+vykacYV+oRY+HSQmHRGHtdCHGNLDA407Mrm2lf1r5DpQG5NuxsTjq1wLfE8BR8kEiZRbMZ0xqU5aE1nZPksK1IDV+Fwr9SeWn/wb/pzex8wUaUBWRzHnTachWGMxakyogNDIQQYviVIpyREAj/sLYMK8Al1jSli2wR7MbF9F+cKncwO16vlrKe3WTl1w2a+00MN5aYUXGYUwAWjz3QJsdvxl4G9Cu2pz+akbJg+OTzSAR5BuHL9n4rF1vQaZPO7BeJww87jBTDdExxkEhyi3BcVMuuYTIrgpjvB/TKGeoDNa7Z862ZOFbPWHY+McJcQt7y4+WUsLXCZUX2tCtUAgZiuYb3dY3KMuDjlrT0D/wYmqz5VRbvly3vjpq/U+9gB59R84uFcUKHRACI25KfVa+w6WvOLj3EFhyC+6qxxlFk="